baseURL = "/myblog/"
theme = "mini"
languageCode = "en-us"
title = "Today...ing"

enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "UA-54433728-4"

# Add your Disqus shortname here.
disqusShortname = ""

sectionPagesMenu = "main"

[Params]
#    author = "Bongjun Hur"
	since = 2019
	googleSiteVerification = "22jTInxspNEYVGE9rJEvduzUaLBCnmsBqFADkXiksEQ"

#[taxonomies]
#  tag = "tags"

[menu]
# Menu links along the sidebar navigation.
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

	[[menu.main]]
		identifier = "tags"
		name = "Tags"
		url = "/tags/"
		weight = 2

	[[menu.main]]
		name = "Archives"
		identifier = "archives"
		url = "/archives/"
		weight = 3

	[[menu.main]]
		name = "Categories"
		identifier = "Categories"
		url = "/Categories/"
		weight = 4


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
